Move download script to root directory
ESMValGroup/ESMValTool_sample_data pull request #9
Opened 2020-11-18 11:38 UTC by stefsmeets

This PR moves the download script to the root directory and gives it a more logical name.

2020-11-18 16:36 UTC, nielsdrost commented on download_sample_data.py
>      cfg_file = Path(__file__).parent.parent / "config.yml"
```suggestion
    cfg_file = Path(__file__).parent / "config.yml"
```

2020-11-18 16:36 UTC, nielsdrost commented on download_sample_data.py
>      cfg_file = Path(__file__).parent.parent / "config.yml"
And: facets_file = Path(__file__).parent / "esmvaltool_sample_data" / "datasets.yml"

2020-11-18 16:37 UTC, nielsdrost commented
I tried to run this script but ran into some trouble.

- This error https://github.com/ESGF/esgf-pyclient/issues/57, solved by adding a few lines at the top to set the SSL version (ee issue)
- The config file and dataset.yml locations do not seem to be correctly specified
- I get a "pyesgf.search.exceptions.EsgfSearchException: Error loading available shards" error.

Then I gave up for today ;-)

2020-11-19 09:01 UTC, stefsmeets commented
> 
> 
> I tried to run this script but ran into some trouble.
> 
>     * This error [ESGF/esgf-pyclient#57](https://github.com/ESGF/esgf-pyclient/issues/57), solved by adding a few lines at the top to set the SSL version (see issue)
> 
>     * The config file and dataset.yml locations do not seem to be correctly specified
> 
>     * I get a "pyesgf.search.exceptions.EsgfSearchException: Error loading available shards" error.
> 
> 
> Then I gave up for today ;-)

Thanks @nielsdrost , good points and it seems like I should have tested this myself first 😅

2020-11-19 11:21 UTC, stefsmeets commented
The `esgf` issues I cannot help with, but I can make sure that `datasets.yml` is correctly referenced. Should work as intended now (or at least it does so on my pc).

2020-11-27 09:25 UTC, bouweandela requested changes
The download script and its configuration file (datsets.yml) belong together, so if you're moving one to the top level, I would also move the other to the top level.

2020-12-01 10:14 UTC, stefsmeets commented
Hi @bouweandela , can you have another look? I think this is ready to merge!

2020-12-01 11:49 UTC, bouweandela commented on download_sample_data.py
> +    facets_file = project_dir / 'esmvaltool_sample_data' / "datasets.yml"
when I try to run the script, I get
```
$ python download_sample_data.py 
Traceback (most recent call last):
  File "download_sample_data.py", line 326, in <module>
    main()
  File "download_sample_data.py", line 288, in main
    with facets_file.open() as file:
  File "/home/bandela/conda/envs/esmvaltool_test_data/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/bandela/conda/envs/esmvaltool_test_data/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'esmvaltool_sample_data/datasets.yml'
```
I think you may have to undo this change

2020-12-01 11:51 UTC, bouweandela reviewed
Thanks for making the changes, I tried to run the script but it failed on loading the configuration file. I also noticed that the documentation on how run the script in CONTRIBUTING.md has not been updated yet.

2020-12-01 12:35 UTC, stefsmeets commented
> 
> 
> Thanks for making the changes, I tried to run the script but it failed on loading the configuration file. I also noticed that the documentation on how run the script in CONTRIBUTING.md has not been updated yet.

Yeah, my bad for not testing if it worked. Should be good now 👍

2020-12-01 20:05 UTC, bouweandela approved these changes

2020-12-01 20:05 UTC, merged